# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:50:56+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class GetzipcodeinfoGetResponse(BaseModel):
    AreaSquareMiles: Optional[str] = None
    City: Optional[str] = None
    Code: Optional[str] = None
    Credits: Optional[str] = None
    ElderlyHouseholdPercent: Optional[str] = None
    FarmerHouseholdPercent: Optional[str] = None
    IncomePercent100k: Optional[str] = None
    IncomePercent200k: Optional[str] = None
    IncomePercent50k: Optional[str] = None
    Latitude: Optional[str] = None
    Longitude: Optional[str] = None
    MarriedHouseholdPercent: Optional[str] = None
    Population: Optional[str] = None
    State: Optional[str] = None
    ZipCode: Optional[str] = None
